### ISSUE TITLE
[Theme] Warning: Creating default object from empty value

### ISSUE THREAD

**Issue by robciucioan** [MachoThemes/pixova-lite#3]
I have this error: Warning: Creating default object from empty value in /home/alelo/public_html/alelo/wp-content/themes/pixova-lite/inc/customizer.php on line 29

**Comment by robciucioan** [comment]
Ion Rutz, nu îmi afișează această eroare. Il poți întreba pe client, te rog, cum a ajuns la această eroare? Mersi!

**Comment by robciucioan** [comment]
Robciuc Ioan, da enable la WP_DEBUG si la erorile / notice-urile de PHP (vezi in setarile WAMP / XAMP )

**Comment by robciucioan** [comment]
Cristian Raiber, am adăugat "true" la WP_DEBUG + am mai adăugat urmatoarele coduri pentru debugging și nu-mi afișează nimic:
```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
@ini_set('display_errors',1);
define('SCRIPT_DEBUG', true);
```

**Comment by robciucioan** [comment]
@cristianraiber, nu-mi afișează eroarea. Țin minte că am testat și pe versiunile anterioare de PHP.

**Comment by cristianraiber** [comment]
Couldn't replicate.
